# Generated by Django 4.0.6 on 2022-07-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
