# Generated by Django 4.0.6 on 2022-07-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
